name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Tag Docker Image
        id: build_image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/portofolio"
          IMAGE_TAG=$(date +%s)
          docker build . -f Containerfile -t "${IMAGE_NAME}:latest" -t "${IMAGE_NAME}:${IMAGE_TAG}"
          echo "image=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "tag=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ${{ env.image }}:${{ env.tag }}
